/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import ClassModel.DBConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Callum
 */
public class HomeForm extends javax.swing.JPanel {

    private JFrame frame;
    private Connection connection;
    private Statement statement;

    /**
     * Creates a new home form
     *
     * @param frame
     */
    public HomeForm(JFrame frame) {
        this.frame = frame;
        DBConnection dbConnection = new DBConnection();
        connection = dbConnection.getConnection();
        initComponents();
        comboStudents.setModel(new javax.swing.DefaultComboBoxModel<>(getStudents()));
        comboStudents.setSelectedItem(null);
    }

    /**
     * This method establishes a connection with the system database and
     * retrieves
     *
     * @return
     */
    public String[] getStudents() {
        try {
            ArrayList<String> studentList = new ArrayList<String>();
            statement = connection.createStatement();
            ResultSet rowCountSet = statement.executeQuery("SELECT COUNT(*) AS count FROM student");
            rowCountSet.next();
            int count = rowCountSet.getInt("count");

            String[] studentArray = new String[count];
            int i = 0;
            ResultSet studentSet = statement.executeQuery("SELECT * FROM student");

            while (studentSet.next()) {
                int studentID = studentSet.getInt("studentID");
                String firstName = studentSet.getString("firstName");
                String lastName = studentSet.getString("lastName");
                studentArray[i] = "" + studentID + ") " + firstName + " " + lastName;
                i++;
            }
            return studentArray;
        } catch (SQLException ex) {
            Logger.getLogger(StudentForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabMain = new javax.swing.JTabbedPane();
        panelStudents = new javax.swing.JPanel();
        btnAddStudent = new javax.swing.JButton();
        btnEditStudent = new javax.swing.JButton();
        comboStudents = new javax.swing.JComboBox<>();
        panelParents = new javax.swing.JPanel();
        btnAddParent = new javax.swing.JButton();
        panelTeachers = new javax.swing.JPanel();
        btnAddTeacher = new javax.swing.JButton();
        btnAddCourse = new javax.swing.JButton();
        btnEnrollStudent = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        btnAddStudent.setText("Add Student");
        btnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentActionPerformed(evt);
            }
        });

        btnEditStudent.setText("Edit Student");
        btnEditStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditStudentActionPerformed(evt);
            }
        });

        comboStudents.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelStudentsLayout = new javax.swing.GroupLayout(panelStudents);
        panelStudents.setLayout(panelStudentsLayout);
        panelStudentsLayout.setHorizontalGroup(
            panelStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStudentsLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btnAddStudent)
                .addGap(41, 41, 41)
                .addGroup(panelStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboStudents, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        panelStudentsLayout.setVerticalGroup(
            panelStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStudentsLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(panelStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddStudent)
                    .addComponent(btnEditStudent))
                .addGap(32, 32, 32)
                .addComponent(comboStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        tabMain.addTab("Students", panelStudents);

        btnAddParent.setText("Add Parent");
        btnAddParent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddParentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelParentsLayout = new javax.swing.GroupLayout(panelParents);
        panelParents.setLayout(panelParentsLayout);
        panelParentsLayout.setHorizontalGroup(
            panelParentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParentsLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btnAddParent)
                .addContainerGap(245, Short.MAX_VALUE))
        );
        panelParentsLayout.setVerticalGroup(
            panelParentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParentsLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btnAddParent)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        tabMain.addTab("Parents", panelParents);

        btnAddTeacher.setText("Add Teacher");
        btnAddTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTeacherActionPerformed(evt);
            }
        });

        btnAddCourse.setText("Add Course");
        btnAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCourseActionPerformed(evt);
            }
        });

        btnEnrollStudent.setText("Enroll Student");
        btnEnrollStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrollStudentActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTeachersLayout = new javax.swing.GroupLayout(panelTeachers);
        panelTeachers.setLayout(panelTeachersLayout);
        panelTeachersLayout.setHorizontalGroup(
            panelTeachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTeachersLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btnAddTeacher)
                .addGap(50, 50, 50)
                .addGroup(panelTeachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelTeachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnEnrollStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        panelTeachersLayout.setVerticalGroup(
            panelTeachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTeachersLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(panelTeachersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddTeacher)
                    .addComponent(btnAddCourse))
                .addGap(20, 20, 20)
                .addComponent(btnEnrollStudent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addContainerGap())
        );

        tabMain.addTab("Teachers", panelTeachers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabMain)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed
        frame.remove(this);
        frame.add(new StudentForm(frame));
        frame.pack();
    }//GEN-LAST:event_btnAddStudentActionPerformed

    private void btnEditStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditStudentActionPerformed
        try {
            Object current = comboStudents.getSelectedItem();
            String student = current.toString();
            System.out.println(student);
            String[] idString = student.split("\\)");
            int studentID = Integer.parseInt(idString[0]);
            frame.remove(this);
            frame.add(new StudentForm(frame, studentID));
            frame.pack();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Please select a student to edit from the drop down menu",
                    "RFID System",
                    JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btnEditStudentActionPerformed

    private void btnAddParentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddParentActionPerformed
        frame.remove(this);
        frame.add(new ParentForm(frame));
        frame.pack();
    }//GEN-LAST:event_btnAddParentActionPerformed

    private void btnAddTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTeacherActionPerformed
        frame.remove(this);
        frame.add(new TeacherForm(frame));
        frame.pack();
    }//GEN-LAST:event_btnAddTeacherActionPerformed

    private void btnAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCourseActionPerformed
        frame.remove(this);
        frame.add(new CourseForm(frame));
        frame.pack();
    }//GEN-LAST:event_btnAddCourseActionPerformed

    private void btnEnrollStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrollStudentActionPerformed
        frame.remove(this);
        frame.add(new EnrollForm(frame));
        frame.pack();
    }//GEN-LAST:event_btnEnrollStudentActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        JOptionPane.showMessageDialog(this,
                "Thank you for using the RFID System",
                "RFID System",
                JOptionPane.PLAIN_MESSAGE);
        frame.remove(this);
        frame.add(new LoginForm(frame));
        frame.pack();
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCourse;
    private javax.swing.JButton btnAddParent;
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnAddTeacher;
    private javax.swing.JButton btnEditStudent;
    private javax.swing.JButton btnEnrollStudent;
    private javax.swing.JButton btnLogout;
    private javax.swing.JComboBox<String> comboStudents;
    private javax.swing.JPanel panelParents;
    private javax.swing.JPanel panelStudents;
    private javax.swing.JPanel panelTeachers;
    private javax.swing.JTabbedPane tabMain;
    // End of variables declaration//GEN-END:variables
}
